# Site settings
title: Roaway's blogs
email: roaway@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  我的日志，想写就写，不想写就不写，想写什么就写什么。瞎写，随便写。
#baseurl: "/jekyll_blog" # the subpath of your site, e.g. /blog/
url: "https://roaway.github.io/" # the base hostname & protocol for your site
url: "/jekyll_blog" # the base hostname & protocol for your site
twitter_username: none
github_username:  roaway

# Build settings
markdown: kramdown
